### ISSUE TITLE
ts-format for network targets

### ISSUE THREAD

**Issue by furiel** [balabit/syslog-ng-ose-guides#19]
There is a little confusion if the syslog-ng documentation about ts-format.

ts-format() parameter is ignored for network targets.

But in the documentation:
https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-destination-network-chapter.html
user could think this parameter would work for network destination:

ts-format()
Type: 	rfc3164, bsd, rfc3339, iso
Default: 	rfc3164

Description: Override the global timestamp format (set in the global ts-format() parameter) for the specific destination. For details, see Section ts-format().

Of course this last part: Section ts-format() is a link to:
https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-options.html#global-option-ts-format
where there is a side note that this option does not work for network targets:

Note
This option applies only to file and file-like destinations. Destinations that use specific protocols (for example, network(), or syslog()) ignore this option. For protocol-like destinations, use a template locally in the destination, or use the proto-template option.

So theoretically users can get this information, but it is somewhat buried. This confuses readers.

As for resolution:
Either we need to remove this ts-format parameter altogether from the network target page.
Or pull the sidenote from the sublink to this specific location: i.e explicitely tell that this parameter is ignored, and add a little suggestion that users can achieve the same behaviour through templates.

**Comment by fekete-robert** [comment]
Hi, Thanks a lot for reporting this problem. 
I'll replace the description of the ts-format option from the network() and syslog() destinations with the note from the global option. I don't want to simply delete the section because the configuration validator of syslog-ng accepts the ts-format option for the network destinations, just ignores it :/

**Comment by furiel** [comment]
Thanks!
