### ISSUE TITLE
ranaming of syslog-ng-debun's man page

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng-ose-guides#23]
I was redirected to here from https://github.com/balabit/syslog-ng/issues/1609

Please follow up the renaming of syslog-debun to syslog-ng-debun.

**Comment by fekete-robert** [comment]
Corrected here: https://github.com/balabit/syslog-ng-ose-guides/commit/55c13887c6dd11d6b6d6093684415b9df1320472
Also related: https://github.com/balabit/syslog-ng-ose-guides/commit/d68b154c80b02f9c29674b8d3a90d29dfb63f910
