### ISSUE TITLE
Broken link leads to old blog sites of Balabit

### ISSUE THREAD

**Issue by abalage** [balabit/syslog-ng-ose-guides#34]
The grouping-by documentation on the following URL mentions a blog post for further examples.

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/79#TOPIC-1094768

Problematic part:
"For another example, see The grouping-by() parser in syslog-ng blog post"

Reference leads to a broken URL: https://czanik.blogs.balabit.com/2016/04/the-grouping_by-parser-in-syslog-ng-3-8/

I think the proper destination would be this one: https://www.syslog-ng.com/community/b/blog/posts/the-grouping-by-parser-in-syslog-ng-3-8

**Comment by fekete-robert** [comment]
Thanks a lot, it's great to hear about you :) 
I've corrected it in the code, should be updated in the 3.20 docs whenever I manage to publish them https://github.com/balabit/syslog-ng-ose-guides/commit/36225a4e0563de6de35571972f132a6100ca4ef5

Cheers!

**Comment by abalage** [comment]
Thanks Robi! I know that the docs are in good hands :)
