### ISSUE TITLE
kv-parser() supports template() but not mentioned in documentation

### ISSUE THREAD

**Issue by abalage** [balabit/syslog-ng-ose-guides#35]
Actually the linux-audit parser utilizes the kv-parser in the background and it specifies template() too.
You can check that SCL to see a working example.

**Comment by fekete-robert** [comment]
Hi, template is listed in the options of kv-parser, or do you mean something else? https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.20/administration-guide/66#TOPIC-1122031

**Comment by abalage** [comment]
Hah. I originally checked 3.19 and I could not find it. I still can't.
Although now I can see that in 3.18 and 3.20 and it is there, just the way you referenced.

- 3.18: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.18/administration-guide/66#TOPIC-1044138
- 3.19: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/66#TOPIC-1094718
- 3.20: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.20/administration-guide/66#TOPIC-1122031

Thanks for the help Robi. This can be closed.
