### ISSUE TITLE
about using 2 csv parser in syslog-ng

### ISSUE THREAD

**Issue by rakeshbare22** [balabit/syslog-ng-ose-guides#94]
lets say i am using 2 csv parser. in both csv the MSG field is same but values are different. now my question is, in my source log when there is unknown ip and also unknown id then which csv will be proceed? because in same source log there is chances of getting unknown ip as well as unknown id. destination i am using is same for both csv.  please suggest me. 
----------  1st csv-------
UNKNOWN_IP,MSG,"RB"
95.105.8.60,MSG,"BT"
183.136.25.46,MSG,"ESA"
102.41.51.109,MSG,"BW"
102.67.77.1,MSG,"BW"

--------2nd csv------
 UNKNOWN_ID,MSG,OTHERS
UNKNOWN_ID,CATEGORY,OTHERS
UNKNOWN_ID,OWA,OTHERS
303668,MSG,"VI"
303668,CATEGORY,Ad
303668,OWA,Yes
303669,MSG,"VT"
303669,CATEGORY,Ad
303669,OWA,Yes
303768,MSG,"VP "

 ------------this is my log statement------------

log {
    source(TI_log);
    parser (p_apache2);
    parser (p_geoipSW);
    rewrite (r_geoipSW);
   rewrite (r_Awww);
  parser (p_ticsv);
  parser (p_swcsv);
  destination(da_932);
};

--------below are the 2 csv parser -----------

parser p_swcsv {
add-contextual-data(selector("${SWA.id}"), database("/etc/syslog-ng/conf.d/swrule.csv"), prefix("SWR."), default-selector("UNKNOWN_ID"));
};

parser p_ticsv {
add-contextual-data(selector("${SWA.clientip}"), database("/etc/syslog-ng/conf.d/ti_rule.csv"), prefix("SWR."), default-selector("UNKNOWN_IP"));
};

**Comment by gaborznagy** [comment]
The parsers will be processed in the order in which they are in the log path, i.e. first  `p_ticsv`, then `p_swcsv`

If you would like to continue this topic, I would recommend starting a discussion under the syslog-ng project itself at https://github.com/syslog-ng/syslog-ng/discussions

Closing this issue.
